<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0-windows</TargetFramework>
    <RootNamespace>GunconUSB</RootNamespace>
    <AssemblyName>GunconUSB</AssemblyName>
    <UseWindowsForms>true</UseWindowsForms>
    <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
    <GenerateAssemblyInfo>false</GenerateAssemblyInfo>
    <EnableDefaultCompileItems>false</EnableDefaultCompileItems>
    <Platforms>AnyCPU;x64;x86</Platforms>
  </PropertyGroup>

  <ItemGroup>
    <Compile Include="GammaManager.cs" />
    <Compile Include="GunconReader.cs" />
    <Compile Include="GunState.cs" />
    <Compile Include="Helper.cs" />
    <Compile Include="Properties\AssemblyInfo.cs" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\WinUSBNet\WinUSBNet.csproj" />
    <ProjectReference Include="..\Guncon3.Core\Guncon3.Core.csproj" />
  </ItemGroup>

</Project>
